services:
  postgres:
    image: postgres:latest
    container_name: survey_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SurveyDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SurveyDb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    container_name: survey_api
    build:
      context: .
      dockerfile: SurveySystem.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=SurveyDb;Username=postgres;Password=postgres;"
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: